# Generated by Django 4.2 on 2026-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('DO', 'Do'), ('DONT', "Don't")], default='no-type', max_length=10)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
