# Generated by Django 4.2 on 2026-02-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltokens',
            old_name='uuid',
            new_name='token',
        ),
    ]
