# Generated by Django 4.2 on 2026-02-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_uuid_personaltokens_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltokens',
            old_name='email',
            new_name='user',
        ),
    ]
