# Generated by Django 4.2 on 2026-02-21 08:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trophies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='trophy-default.png', upload_to='trophies')),
                ('information', models.TextField(default='No information yet')),
                ('bio', models.TextField(default='No bio yet')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trophy_type', models.CharField(choices=[('DO', 'Do'), ('DONT', "Don't")], default='no-type', max_length=10)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
