# Generated by Django 4.2 on 2026-05-30 14:30

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_time', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('alltime', 'All Time')], max_length=20)),
                ('required_stat', models.CharField(choices=[('tasks_created_Do', 'Do Created'), ('tasks_completed_Do', 'Do Completed'), ('tasks_deleted_Do', 'Do Deleted'), ('tasks_created_Dont', 'Dont Created'), ('tasks_completed_Dont', 'Dont Completed'), ('tasks_deleted_Dont', 'Dont Deleted')], max_length=50)),
                ('required_value', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='trophy-default.png', upload_to='trophies')),
                ('information', models.TextField(default='No information yet')),
                ('bio', models.TextField(default='No bio yet')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trophy_type', models.CharField(choices=[('DO', 'Do'), ('DONT', "Don't")], default='no-type', max_length=10)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophies.trophies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
