# Generated by Django 4.2 on 2025-12-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophies',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='trophies',
            name='bio',
            field=models.TextField(default='No bio yet'),
        ),
        migrations.AddField(
            model_name='trophies',
            name='trophy_type',
            field=models.CharField(choices=[('DO', 'Do'), ('DONT', "Don't")], default='no-type', max_length=10),
        ),
        migrations.AlterField(
            model_name='trophies',
            name='information',
            field=models.TextField(default='No information yet'),
        ),
    ]
