# Generated by Django 4.2 on 2025-12-28 09:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0002_alter_trophies_options_trophies_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophies',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
